name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover -s tests -p 'test.py'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Deploy application to Heroku
      uses: dhusyanthkarthic/heroku-deploy@main
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: 'News_ERIC'
